# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'XtalxplorerMainWindowUI.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_XtalxplorerMainWindow(object):
    def setupUi(self, XtalxplorerMainWindow):
        XtalxplorerMainWindow.setObjectName("XtalxplorerMainWindow")
        XtalxplorerMainWindow.resize(1024, 740)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(XtalxplorerMainWindow.sizePolicy().hasHeightForWidth())
        XtalxplorerMainWindow.setSizePolicy(sizePolicy)
        XtalxplorerMainWindow.setMinimumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/PowPySol.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        XtalxplorerMainWindow.setWindowIcon(icon)
        self.container = QtWidgets.QWidget(XtalxplorerMainWindow)
        self.container.setMinimumSize(QtCore.QSize(780, 580))
        self.container.setObjectName("container")
        self.gridLayout = QtWidgets.QGridLayout(self.container)
        self.gridLayout.setObjectName("gridLayout")
        self.hLayout_main = QtWidgets.QHBoxLayout()
        self.hLayout_main.setObjectName("hLayout_main")
        self.vLayout_tools = QtWidgets.QVBoxLayout()
        self.vLayout_tools.setObjectName("vLayout_tools")
        self.toolButton_open = QtWidgets.QToolButton(self.container)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Document-open.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_open.setIcon(icon1)
        self.toolButton_open.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_open.setObjectName("toolButton_open")
        self.vLayout_tools.addWidget(self.toolButton_open)
        self.toolButton_copyStructure = QtWidgets.QToolButton(self.container)
        self.toolButton_copyStructure.setObjectName("toolButton_copyStructure")
        self.vLayout_tools.addWidget(self.toolButton_copyStructure)
        self.progressBar = QtWidgets.QProgressBar(self.container)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setOrientation(QtCore.Qt.Vertical)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.progressBar.setObjectName("progressBar")
        self.vLayout_tools.addWidget(self.progressBar)
        self.hLayout_main.addLayout(self.vLayout_tools)
        self.vLayout_main = QtWidgets.QVBoxLayout()
        self.vLayout_main.setObjectName("vLayout_main")
        self.hLayout_top = QtWidgets.QHBoxLayout()
        self.hLayout_top.setObjectName("hLayout_top")
        self.tabWidget = QtWidgets.QTabWidget(self.container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setObjectName("tabWidget")
        self.tabParams = QtWidgets.QWidget()
        self.tabParams.setObjectName("tabParams")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabParams)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_params = QtWidgets.QGridLayout()
        self.gridLayout_params.setObjectName("gridLayout_params")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lstWidget_atoms = QtWidgets.QListWidget(self.tabParams)
        self.lstWidget_atoms.setMinimumSize(QtCore.QSize(30, 100))
        self.lstWidget_atoms.setMaximumSize(QtCore.QSize(90, 16777215))
        self.lstWidget_atoms.setAlternatingRowColors(True)
        self.lstWidget_atoms.setObjectName("lstWidget_atoms")
        self.horizontalLayout.addWidget(self.lstWidget_atoms)
        self.dss_x = DoubleSpinSlider(self.tabParams)
        self.dss_x.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dss_x.sizePolicy().hasHeightForWidth())
        self.dss_x.setSizePolicy(sizePolicy)
        self.dss_x.setMinimumSize(QtCore.QSize(30, 100))
        self.dss_x.setObjectName("dss_x")
        self.horizontalLayout.addWidget(self.dss_x)
        self.dss_y = DoubleSpinSlider(self.tabParams)
        self.dss_y.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dss_y.sizePolicy().hasHeightForWidth())
        self.dss_y.setSizePolicy(sizePolicy)
        self.dss_y.setMinimumSize(QtCore.QSize(30, 100))
        self.dss_y.setObjectName("dss_y")
        self.horizontalLayout.addWidget(self.dss_y)
        self.dss_z = DoubleSpinSlider(self.tabParams)
        self.dss_z.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dss_z.sizePolicy().hasHeightForWidth())
        self.dss_z.setSizePolicy(sizePolicy)
        self.dss_z.setMinimumSize(QtCore.QSize(30, 100))
        self.dss_z.setObjectName("dss_z")
        self.horizontalLayout.addWidget(self.dss_z)
        self.dss_uiso = DoubleSpinSlider(self.tabParams)
        self.dss_uiso.setEnabled(False)
        self.dss_uiso.setMinimumSize(QtCore.QSize(30, 100))
        self.dss_uiso.setObjectName("dss_uiso")
        self.horizontalLayout.addWidget(self.dss_uiso)
        self.vLayout_paramButtons = QtWidgets.QVBoxLayout()
        self.vLayout_paramButtons.setObjectName("vLayout_paramButtons")
        self.groupBox_structureSelect = QtWidgets.QGroupBox(self.tabParams)
        self.groupBox_structureSelect.setMinimumSize(QtCore.QSize(0, 70))
        self.groupBox_structureSelect.setObjectName("groupBox_structureSelect")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_structureSelect)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 20, 131, 54))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vLayout_structureSelect = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vLayout_structureSelect.setContentsMargins(0, 0, 0, 0)
        self.vLayout_structureSelect.setObjectName("vLayout_structureSelect")
        self.radioButton_structure1 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_structure1.setChecked(True)
        self.radioButton_structure1.setObjectName("radioButton_structure1")
        self.vLayout_structureSelect.addWidget(self.radioButton_structure1)
        self.radioButton_structure2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_structure2.setEnabled(False)
        self.radioButton_structure2.setObjectName("radioButton_structure2")
        self.vLayout_structureSelect.addWidget(self.radioButton_structure2)
        self.vLayout_paramButtons.addWidget(self.groupBox_structureSelect)
        self.hLayout_Cbuttons = QtWidgets.QHBoxLayout()
        self.hLayout_Cbuttons.setObjectName("hLayout_Cbuttons")
        self.toolButton_updateParams = QtWidgets.QToolButton(self.tabParams)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Media-playback-start.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.toolButton_updateParams.setIcon(icon2)
        self.toolButton_updateParams.setObjectName("toolButton_updateParams")
        self.hLayout_Cbuttons.addWidget(self.toolButton_updateParams)
        self.toolButton_randomStructure = QtWidgets.QToolButton(self.tabParams)
        self.toolButton_randomStructure.setIcon(icon)
        self.toolButton_randomStructure.setObjectName("toolButton_randomStructure")
        self.hLayout_Cbuttons.addWidget(self.toolButton_randomStructure)
        self.vLayout_paramButtons.addLayout(self.hLayout_Cbuttons)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vLayout_paramButtons.addItem(spacerItem)
        self.checkBox_autoupdateStructure = QtWidgets.QCheckBox(self.tabParams)
        self.checkBox_autoupdateStructure.setObjectName("checkBox_autoupdateStructure")
        self.vLayout_paramButtons.addWidget(self.checkBox_autoupdateStructure)
        self.checkBox_showLabels = QtWidgets.QCheckBox(self.tabParams)
        self.checkBox_showLabels.setObjectName("checkBox_showLabels")
        self.vLayout_paramButtons.addWidget(self.checkBox_showLabels)
        self.checkBox_suffix = QtWidgets.QCheckBox(self.tabParams)
        self.checkBox_suffix.setObjectName("checkBox_suffix")
        self.vLayout_paramButtons.addWidget(self.checkBox_suffix)
        self.horizontalLayout.addLayout(self.vLayout_paramButtons)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 2)
        self.horizontalLayout.setStretch(3, 2)
        self.horizontalLayout.setStretch(4, 2)
        self.horizontalLayout.setStretch(5, 2)
        self.gridLayout_params.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_params, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabParams, "")
        self.tab_xtalData = QtWidgets.QWidget()
        self.tab_xtalData.setObjectName("tab_xtalData")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_xtalData)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_xtalData = QtWidgets.QGridLayout()
        self.gridLayout_xtalData.setObjectName("gridLayout_xtalData")
        self.treeView_xtalData = QtWidgets.QTreeView(self.tab_xtalData)
        self.treeView_xtalData.setObjectName("treeView_xtalData")
        self.gridLayout_xtalData.addWidget(self.treeView_xtalData, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_xtalData, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_xtalData, "")
        self.tab_log = QtWidgets.QWidget()
        self.tab_log.setObjectName("tab_log")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_log)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_log = QtWidgets.QGridLayout()
        self.gridLayout_log.setObjectName("gridLayout_log")
        self.textEdit_log = QtWidgets.QTextEdit(self.tab_log)
        self.textEdit_log.setObjectName("textEdit_log")
        self.gridLayout_log.addWidget(self.textEdit_log, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_log, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_log, "")
        self.hLayout_top.addWidget(self.tabWidget)
        self.Q_structure_view = QtWidgets.QWidget(self.container)
        self.Q_structure_view.setMinimumSize(QtCore.QSize(400, 300))
        self.Q_structure_view.setBaseSize(QtCore.QSize(400, 300))
        self.Q_structure_view.setObjectName("Q_structure_view")
        self.hLayout_top.addWidget(self.Q_structure_view)
        self.hLayout_top.setStretch(0, 1)
        self.vLayout_main.addLayout(self.hLayout_top)
        self.line = QtWidgets.QFrame(self.container)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.vLayout_main.addWidget(self.line)
        self.hLayout_bottom = QtWidgets.QHBoxLayout()
        self.hLayout_bottom.setObjectName("hLayout_bottom")
        self.vLayout_mainvis = QtWidgets.QVBoxLayout()
        self.vLayout_mainvis.setObjectName("vLayout_mainvis")
        self.hLayout_xyselector = QtWidgets.QHBoxLayout()
        self.hLayout_xyselector.setObjectName("hLayout_xyselector")
        self.label_xaxis = QtWidgets.QLabel(self.container)
        self.label_xaxis.setObjectName("label_xaxis")
        self.hLayout_xyselector.addWidget(self.label_xaxis)
        self.comboBox_x = QtWidgets.QComboBox(self.container)
        self.comboBox_x.setObjectName("comboBox_x")
        self.hLayout_xyselector.addWidget(self.comboBox_x)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hLayout_xyselector.addItem(spacerItem1)
        self.checkBox_fine = QtWidgets.QCheckBox(self.container)
        self.checkBox_fine.setObjectName("checkBox_fine")
        self.hLayout_xyselector.addWidget(self.checkBox_fine)
        self.checkBox_autoupdateRPlots = QtWidgets.QCheckBox(self.container)
        self.checkBox_autoupdateRPlots.setObjectName("checkBox_autoupdateRPlots")
        self.hLayout_xyselector.addWidget(self.checkBox_autoupdateRPlots)
        self.toolButton_updateRPlots = QtWidgets.QToolButton(self.container)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Media-playback-start.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_updateRPlots.setIcon(icon3)
        self.toolButton_updateRPlots.setObjectName("toolButton_updateRPlots")
        self.hLayout_xyselector.addWidget(self.toolButton_updateRPlots)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hLayout_xyselector.addItem(spacerItem2)
        self.label_yaxis = QtWidgets.QLabel(self.container)
        self.label_yaxis.setObjectName("label_yaxis")
        self.hLayout_xyselector.addWidget(self.label_yaxis)
        self.comboBox_y = QtWidgets.QComboBox(self.container)
        self.comboBox_y.setObjectName("comboBox_y")
        self.hLayout_xyselector.addWidget(self.comboBox_y)
        self.vLayout_mainvis.addLayout(self.hLayout_xyselector)
        self.hLayout_topView = QtWidgets.QHBoxLayout()
        self.hLayout_topView.setObjectName("hLayout_topView")
        self.dss_dmin = DoubleSpinSlider(self.container)
        self.dss_dmin.setObjectName("dss_dmin")
        self.hLayout_topView.addWidget(self.dss_dmin)
        self.Q_top_view = QtWidgets.QWidget(self.container)
        self.Q_top_view.setMinimumSize(QtCore.QSize(400, 300))
        self.Q_top_view.setBaseSize(QtCore.QSize(400, 300))
        self.Q_top_view.setObjectName("Q_top_view")
        self.hLayout_topView.addWidget(self.Q_top_view)
        self.vLayout_mainvis.addLayout(self.hLayout_topView)
        self.vLayout_mainvis.setStretch(1, 1)
        self.hLayout_bottom.addLayout(self.vLayout_mainvis)
        self.line_2 = QtWidgets.QFrame(self.container)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.hLayout_bottom.addWidget(self.line_2)
        self.Q_3D_View = QtWidgets.QWidget(self.container)
        self.Q_3D_View.setMinimumSize(QtCore.QSize(400, 300))
        self.Q_3D_View.setBaseSize(QtCore.QSize(400, 300))
        self.Q_3D_View.setObjectName("Q_3D_View")
        self.hLayout_bottom.addWidget(self.Q_3D_View)
        self.hLayout_bottom.setStretch(0, 1)
        self.vLayout_main.addLayout(self.hLayout_bottom)
        self.vLayout_main.setStretch(0, 1)
        self.vLayout_main.setStretch(2, 1)
        self.hLayout_main.addLayout(self.vLayout_main)
        self.gridLayout.addLayout(self.hLayout_main, 0, 0, 1, 1)
        XtalxplorerMainWindow.setCentralWidget(self.container)
        self.menubar = QtWidgets.QMenuBar(XtalxplorerMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 30))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.menu_help = QtWidgets.QMenu(self.menubar)
        self.menu_help.setObjectName("menu_help")
        self.menu_Job = QtWidgets.QMenu(self.menubar)
        self.menu_Job.setObjectName("menu_Job")
        XtalxplorerMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(XtalxplorerMainWindow)
        self.statusbar.setObjectName("statusbar")
        XtalxplorerMainWindow.setStatusBar(self.statusbar)
        self.action_about = QtWidgets.QAction(XtalxplorerMainWindow)
        self.action_about.setObjectName("action_about")
        self.action_open = QtWidgets.QAction(XtalxplorerMainWindow)
        self.action_open.setIcon(icon1)
        self.action_open.setPriority(QtWidgets.QAction.HighPriority)
        self.action_open.setObjectName("action_open")
        self.action_quit = QtWidgets.QAction(XtalxplorerMainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/System-log-out-2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_quit.setIcon(icon4)
        self.action_quit.setObjectName("action_quit")
        self.action_run = QtWidgets.QAction(XtalxplorerMainWindow)
        self.action_run.setIcon(icon3)
        self.action_run.setObjectName("action_run")
        self.action_pause = QtWidgets.QAction(XtalxplorerMainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/Media-playback-pause.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_pause.setIcon(icon5)
        self.action_pause.setObjectName("action_pause")
        self.action_stop = QtWidgets.QAction(XtalxplorerMainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/Media-playback-stop.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_stop.setIcon(icon6)
        self.action_stop.setObjectName("action_stop")
        self.menu_file.addAction(self.action_open)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_quit)
        self.menu_help.addAction(self.action_about)
        self.menu_Job.addAction(self.action_run)
        self.menu_Job.addAction(self.action_pause)
        self.menu_Job.addAction(self.action_stop)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_Job.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(XtalxplorerMainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.action_quit.triggered['bool'].connect(XtalxplorerMainWindow.close)
        self.action_about.triggered.connect(XtalxplorerMainWindow.about)
        self.action_open.triggered.connect(XtalxplorerMainWindow.browse_structure)
        self.toolButton_open.clicked.connect(XtalxplorerMainWindow.browse_structure)
        self.lstWidget_atoms.currentRowChanged['int'].connect(XtalxplorerMainWindow.load_atom_params)
        self.toolButton_updateParams.clicked.connect(XtalxplorerMainWindow.update_params)
        self.checkBox_autoupdateStructure.toggled['bool'].connect(XtalxplorerMainWindow.handle_autoupdate_structure)
        self.checkBox_showLabels.toggled['bool'].connect(XtalxplorerMainWindow.invalidate_cached_params)
        self.checkBox_suffix.toggled['bool'].connect(XtalxplorerMainWindow.invalidate_cached_params)
        self.checkBox_autoupdateRPlots.toggled['bool'].connect(XtalxplorerMainWindow.handle_autoupdate_r_plots)
        self.radioButton_structure1.toggled['bool'].connect(XtalxplorerMainWindow._load_structure)
        self.toolButton_randomStructure.clicked.connect(XtalxplorerMainWindow.randomise_structure)
        self.toolButton_copyStructure.clicked.connect(XtalxplorerMainWindow._copy_structure)
        self.toolButton_updateRPlots.clicked.connect(XtalxplorerMainWindow.update_rplots)
        self.checkBox_fine.clicked.connect(XtalxplorerMainWindow.update_rplots)
        QtCore.QMetaObject.connectSlotsByName(XtalxplorerMainWindow)

    def retranslateUi(self, XtalxplorerMainWindow):
        _translate = QtCore.QCoreApplication.translate
        XtalxplorerMainWindow.setWindowTitle(_translate("XtalxplorerMainWindow", "MainWindow"))
        self.toolButton_open.setText(_translate("XtalxplorerMainWindow", "open file"))
        self.toolButton_copyStructure.setText(_translate("XtalxplorerMainWindow", "Copy"))
        self.groupBox_structureSelect.setTitle(_translate("XtalxplorerMainWindow", "Structure select:"))
        self.radioButton_structure1.setText(_translate("XtalxplorerMainWindow", "trial str&ucture"))
        self.radioButton_structure2.setText(_translate("XtalxplorerMainWindow", "target structure"))
        self.toolButton_updateParams.setText(_translate("XtalxplorerMainWindow", "..."))
        self.toolButton_randomStructure.setToolTip(_translate("XtalxplorerMainWindow", "randomise structure"))
        self.toolButton_randomStructure.setText(_translate("XtalxplorerMainWindow", "..."))
        self.checkBox_autoupdateStructure.setText(_translate("XtalxplorerMainWindow", "Autoupdate -->"))
        self.checkBox_showLabels.setText(_translate("XtalxplorerMainWindow", "Atom labels"))
        self.checkBox_suffix.setToolTip(_translate("XtalxplorerMainWindow", "Add suffixes to symmetry generated atom labels"))
        self.checkBox_suffix.setText(_translate("XtalxplorerMainWindow", "suffix symm.eq."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabParams), _translate("XtalxplorerMainWindow", "Coordinates"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_xtalData), _translate("XtalxplorerMainWindow", "Crystal data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_log), _translate("XtalxplorerMainWindow", "Log"))
        self.label_xaxis.setText(_translate("XtalxplorerMainWindow", "x-axis:"))
        self.checkBox_fine.setText(_translate("XtalxplorerMainWindow", "fine"))
        self.checkBox_autoupdateRPlots.setText(_translate("XtalxplorerMainWindow", "Autoupdate"))
        self.toolButton_updateRPlots.setText(_translate("XtalxplorerMainWindow", "..."))
        self.label_yaxis.setText(_translate("XtalxplorerMainWindow", "y-axis:"))
        self.menu_file.setTitle(_translate("XtalxplorerMainWindow", "&File"))
        self.menu_help.setTitle(_translate("XtalxplorerMainWindow", "&Help"))
        self.menu_Job.setTitle(_translate("XtalxplorerMainWindow", "&Job"))
        self.action_about.setText(_translate("XtalxplorerMainWindow", "&About"))
        self.action_about.setStatusTip(_translate("XtalxplorerMainWindow", "About this programme"))
        self.action_about.setShortcut(_translate("XtalxplorerMainWindow", "Ctrl+A"))
        self.action_open.setText(_translate("XtalxplorerMainWindow", "&Open"))
        self.action_open.setShortcut(_translate("XtalxplorerMainWindow", "Ctrl+O"))
        self.action_quit.setText(_translate("XtalxplorerMainWindow", "&Quit"))
        self.action_quit.setStatusTip(_translate("XtalxplorerMainWindow", "Exit this programme"))
        self.action_quit.setShortcut(_translate("XtalxplorerMainWindow", "Ctrl+Q"))
        self.action_run.setText(_translate("XtalxplorerMainWindow", "&Run"))
        self.action_run.setShortcut(_translate("XtalxplorerMainWindow", "Ctrl+R"))
        self.action_pause.setText(_translate("XtalxplorerMainWindow", "&Pause"))
        self.action_pause.setShortcut(_translate("XtalxplorerMainWindow", "Ctrl+P"))
        self.action_stop.setText(_translate("XtalxplorerMainWindow", "&Stop"))
        self.action_stop.setShortcut(_translate("XtalxplorerMainWindow", "Ctrl+S"))

from gui.doublespinslider import DoubleSpinSlider
import gui_rc
